set-option -sg escape-time 10
set-option -g focus-events on
set-option -ga terminal-overrides ",xterm-256color*:Tc"
set-option -g default-terminal "screen-256color"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g mouse on
set-option -g prefix M-x
unbind-key C-b

bind-key M-x send-prefix

unbind-key %

bind v split-window -h -c "#{pane_current_path}"  # horizontal split
bind s split-window -v -c "#{pane_current_path}"  # vertical split

unbind-key '"'

bind r source-file ~/.tmux.conf \; display "Reloaded!"

set -g base-index 1
setw -g pane-base-index 1

set -g status-position bottom
set -g status-justify left
 set -g status-style 'fg=red'

set -g status-left ''
set -g status-left-length 10

 set -g status-right-style 'fg=black bg=yellow'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

 set -g window-status-current-style 'fg=colour0,bg=colour45'
setw -g window-status-current-format ' #I #W #F '

 setw -g window-status-style 'fg=red bg=black'
 setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

 setw -g window-status-bell-style 'fg=yellow bg=red bold'

bind \` switch-client -t'{marked}'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


bind c new-window -c "#{window_current_path}"

setw -g mode-keys vi

bind Escape copy-mode            # Enter copy mode with Prefix + Escape
bind p paste-buffer              # Paste the most recent buffer
bind + delete-buffer             # Delete the most recent buffer

# Copy mode keybindings using the newer 'copy-mode-vi' table
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi V send -X rectangle-toggle
bind -T copy-mode-vi Y send -X copy-end-of-line

run '~/.tmux/plugins/tpm/tpm'
